services:
  app:
    build:
      context: .
      args:
        PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      PORT: "${PORT}"
      MONGO_URI: "mongodb://${MONGO_APP_USERNAME}:${MONGO_APP_PASSWORD}@mongo:${MONGO_PORT}/${DB_NAME}?authSource=${DB_NAME}"
      DB_NAME: "${DB_NAME}"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_TTL: "${JWT_TTL}"
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    ports:
      - "${MONGO_PORT}:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${DB_NAME}"
    volumes:
      - ./data/mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
